---
title: "Where are the bands I've been listening to lately from"
author: "John Ray"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: sandstone
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(googlesheets4)
library(flexdashboard)
library(plotly)
library(maps)
library(knitr)

# Make googlesheets4 not try to authenticate, since we're using a public sheet
sheets_deauth()
```

```{r get-data, message=FALSE, include=FALSE}
# The 1RKNn84xVLUanhGyX8DPvDSd8zt4GX_eBmK2ZX2nf0BI comes from the shared link
# URL from Google Sheets. You can also refer to sheets by name if you're
# authenticated into your account. See the googlesheets4 documentation for more
# In the current version of googlesheets4, this will require you to sign into Google
# details
remote_data <- read_sheet("https://docs.google.com/spreadsheets/d/1XZ6n-2_RhQnu_ZwuUSUIhLIezA5y0J9MTPd0qJ1Alc0", sheet = 'full')
remote_data$lab <- paste0("Band: ", remote_data$band,"\nCity: ", remote_data$city, "\nListen at: ", remote_data$url)
```

## Row {data-height=800}
-------------------------------------

### Band hometowns

```{r}
# Get a small map of the world
world <- map_data("world")

# Plot the area that contains my data
the_plot <- ggplot(remote_data) +
  borders("world", xlim = c(min(remote_data$lon) - 5, max(remote_data$lon) + 5), ylim = c(min(remote_data$lat) - 5, max(remote_data$lat) + 5)) +
  geom_jitter(aes(x = lon, y = lat, text = lab), width = .6, size = 2, color = "#CF6F55") +
  theme_void() +
  coord_fixed(1.3)

# Put ggplotly() inside renderPlotly({})
renderPlotly({
  ggplotly(the_plot, tooltip = "text")
})
```

## Row {data-height=200 .tabset .tabset-fade}
-------------------------------------

### New bands {.value-box}

```{r}
# Find the number of unique categories
n_bands <- remote_data %>% distinct(band) %>% nrow()
n_cities <- remote_data %>% distinct(city) %>% nrow()
vb_val <- paste0(n_bands, " bands from ", n_cities, " different places")

# Show the number in a special valueBox (note the {.value-box} CSS class
# above—that applies the CSS class to the HTML output and makes it render
# correctly)
valueBox(value = vb_val, icon = "fas fa-users")
```

### The data

```{r}
kable(remote_data[, c('band', 'city', 'url')], caption = "These are the bands plotted on the map")
```